spring:
  application:
    name: data-access

  datasource:
    url: jdbc:mariadb://localhost:3306/gustatour
    username: root
    password: Boubou.17042002
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

